#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/sinasio/local/google-cloud-sdk/path.zsh.inc' ]; then
    source '/home/sinasio/local/google-cloud-sdk/path.zsh.inc';
fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/sinasio/local/google-cloud-sdk/completion.zsh.inc' ]; then
    source '/home/sinasio/local/google-cloud-sdk/completion.zsh.inc';
fi

# Enable completion for kubectl
if (( $+commands[kubectl] )); then
    source <(kubectl completion zsh)
fi

# Enable completion for pipenv
# FIXME: disabled because it is SUPER SLOW!!
#if (( $+commands[pipenv] )); then
    #eval "$(pipenv --completion)"
#fi

if [ -f "${HOME}/.zsh_plugins.sh" ]; then
    source ${HOME}/.zsh_plugins.sh
fi


workon-ionic() {
    nvm use default

    local STUDIO_HOME="$HOME/Applications/android-studio"
    local ANDROID_SDK_HOME="$HOME/Applications/Android/Sdk"
    export JAVA_HOME="$STUDIO_HOME/jre"
    export PATH="$STUDIO_HOME/bin:$PATH"
    export PATH="$ANDROID_SDK_HOME/tools:$PATH"
    export PATH="$ANDROID_SDK_HOME/platform-tools:$PATH"
    export PATH="/opt/gradle/gradle-6.0.1/bin:$PATH"
}

couscous-update-tag() {
    local current_version=${1:?"Specify current version"}
    local next_version=${2:?"Specify next version"}
    echo "Upgrade tags from ${current_version} to ${next_version}"
    rg -l ${current_version} | xargs sed -i "s/${current_version}/${next_version}/g"
}
